---
version: '3'
services:
  flask:
    image: backend-challenge:local
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/local/src
    ports:
      - ${PORT:-5000}:5000
    command:
      - python
      - main.py
